### ISSUE TITLE
Thanks for your project! Working good also with Python 3.8

### ISSUE THREAD

**Issue by eliafino** [edrickrenan/telegram-forwarder#1]
Thanks very much for this project!!!

**Comment by edrickrenan** [comment]
You're welcome, @eliafino. 

I'll be improving the code in future, adding some tests and possibly new features. Feel free to contribute to the project if you're interested.

**Comment by edumariano2000** [comment]
@edrickrenano is there any way around heroku? as he is banning

**Comment by Juninhoww2** [comment]
a good project sir

**Comment by eliafino** [comment]
> You're welcome, @eliafino.
> 
> I'll be improving the code in future, adding some tests and possibly new features. Feel free to contribute to the project if you're interested.

Hi, there is a way to "copy & paste" posts in a channel/group with forwarding disabled?

"ERROR    [400 Bad Request]: [400 CHAT_FORWARDS_RESTRICTED] (caused by "messages.ForwardMessages")"

**Comment by edrickrenan** [comment]
Hey @eliafino. I'll push some changes soon that will allow you to do it.

**Comment by eliafino** [comment]
> Hey @eliafino. I'll push some changes soon that will allow you to do it.

Great! Thank you very much!

**Comment by edrickrenan** [comment]
@eliafino, pushed the change now. I hope it fixes your issue. You might need to run ` pip3 install -r requirements.txt --upgrade` before restarting the application.

**Comment by eliafino** [comment]
Thanks @edrickrenan but not run in a clean installation and with requirements installed:

`Traceback (most recent call last):
  File "/usr/local/bin/telegram-forwarder/main.py", line 32, in <module>
    app.run()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/client.py", line 564, in load_session
    await self.storage.open()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/memory_storage.py", line 59, in open
    dc_id, api_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
struct.error: unpack requires a buffer of 271 bytes
`

**Comment by eliafino** [comment]
New line 10: app = Client(name="telegram_forwarder", session_string=app_config.session, api_id=app_config.api_id, api_hash=app_config.api_hash)

Old line 10: app = Client(app_config.session, app_config.api_id, app_config.api_hash)

**Comment by eliafino** [comment]
Ok, pull requested 😉

It's possible to add a new line at top of paste message, with channel ID and channel name?

**Comment by edrickrenan** [comment]
I think so. Let me check that. 

Thanks for the PR.
